### ISSUE TITLE
curriculum differs from ossu/computer-science?

### ISSUE THREAD

**Issue by DavidScales** [ossu/ossu-client#63]
Sorry if this I'm misreading something, but it looks like the courses in this app don't map entirely to those in [https://github.com/ossu/computer-science](https://github.com/ossu/computer-science)?

Is the latter the source of truth or is there something I'm missing?

**Comment by SergeyKhval** [comment]
Hi, @DavidScales 
App is currently out of date with the curriculum. Please treat [this github repo](https://github.com/ossu/computer-science) as the source of truth
