### ISSUE TITLE
Mathematical Thinking Course Doesn't Resolve

### ISSUE THREAD

**Issue by jaritars1** [ossu/ossu-client#71]
The link in the course catalog is: https://www.edx.org/course/effective-thinking-through-mathematics-utaustinx-ut-9-01x. 

This is the new course:https://www.edx.org/learn/math/the-university-of-texas-at-austin-effective-thinking-through-mathematics-2

**Comment by waciumawanjohi** [comment]
Fix is in the curriculum: https://github.com/ossu/computer-science/commit/d27b2df

This repo does not represent the current state of the curriculum. Use cs.ossu.dev
